import { useQuery } from "@tanstack/react-query";
import { useTranslation } from "react-i18next";

import { GamePlayerLevel, GameStatus, GameType } from "@/constants/game";
import GameQueryKeys from "./gameKeys";
import { gameListAdapter } from "./gameAdapter";

import type { Game, Player } from "@/types/Game";
import type { QueryOptions } from "../types";
import type { GameListPayload, GameListItem } from "./types";

export function useGameListQueries(
  payload: GameListPayload,
  options = {} as QueryOptions<GameListItem[]>
) {
  const { t } = useTranslation("GameList");

  return useQuery({
    queryKey: GameQueryKeys.GameList(payload),
    queryFn: () =>
      new Promise<Game[]>((resolve) => {
        setTimeout(() => {
          const mockPlayers: Player[] = [
            {
              id: 1,
              avatar:
                "https://images.unsplash.com/photo-1633332755192-727a05c4013d?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1160&q=80",
              createdAt: new Date(),
              updatedAt: new Date(),
              isDeleted: false,
              isActive: true,
              name: "Player 1",
              level: GamePlayerLevel.Amateur,
            },
            {
              id: 2,
              avatar:
                "https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1160&q=80",
              createdAt: new Date(),
              updatedAt: new Date(),
              isDeleted: false,
              isActive: true,
              name: "Player 2",
              level: GamePlayerLevel.Master,
            },
            {
              id: 3,
              avatar:
                "https://images.unsplash.com/photo-1570295999919-56ceb5ecca61?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1160&q=80",
              createdAt: new Date(),
              updatedAt: new Date(),
              isDeleted: false,
              isActive: true,
              name: "Player 3",
              level: GamePlayerLevel.Legend,
            },
            {
              id: 4,
              avatar:
                "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1287&q=80",
              createdAt: new Date(),
              updatedAt: new Date(),
              isDeleted: false,
              isActive: true,
              name: "Player 4",
              level: GamePlayerLevel.Amateur,
            },
            {
              id: 5,
              avatar:
                "https://images.unsplash.com/photo-1544005313-94ddf0286df2?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1288&q=80",
              createdAt: new Date(),
              updatedAt: new Date(),
              isDeleted: false,
              isActive: true,
              name: "Player 5",
              level: GamePlayerLevel.Amateur,
            },
            {
              id: 6,
              avatar:
                "https://images.unsplash.com/photo-1544005313-94ddf0286df2?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1288&q=80",
              createdAt: new Date(),
              updatedAt: new Date(),
              isDeleted: false,
              isActive: true,
              name: "Player 6",
              level: GamePlayerLevel.Amateur,
            },
            {
              id: 7,
              avatar:
                "https://images.unsplash.com/photo-1544005313-94ddf0286df2?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1288&q=80",
              createdAt: new Date(),
              updatedAt: new Date(),
              isDeleted: false,
              isActive: true,
              name: "Player 7",
              level: GamePlayerLevel.Amateur,
            },
          ];

          resolve([
            {
              id: 1,
              ownerId: 1,
              players: [
                mockPlayers[0],
                mockPlayers[1],
                mockPlayers[2],
                mockPlayers[4],
                mockPlayers[3],
              ],
              gameType: GameType.Friendly,
              gameStatus: GameStatus.Active,
              gamePlayerLevel: GamePlayerLevel.Amateur,
              description: "Friendly game",
              images: [
                "https://images.unsplash.com/photo-1575361204480-aadea25e6e68?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1171&q=80",
                "https://images.unsplash.com/photo-1508098682722-e99c43a406b2?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1170&q=80",
                "https://images.unsplash.com/photo-1551958219-acbc608c6377?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1170&q=80",
              ],
              field: {
                id: 1,
                name: "Field 1",
                address: "Address 1",
                latitude: 100,
                longitude: 100,
                createdAt: new Date(),
                updatedAt: new Date(),
                isDeleted: false,
                isActive: true,
              },
              createdAt: new Date(),
              updatedAt: new Date(),
              isDeleted: false,
              isActive: true,
              isPublic: true,
              playerPerTeam: 4,
              price: 100,
              currency: "USD",
              isFree: true,
              isPaid: false,
              startTime: new Date(),
              duration: 100,
            },
            {
              id: 2,
              ownerId: 2,
              players: [
                mockPlayers[1],
                mockPlayers[2],
                mockPlayers[3],
                mockPlayers[4],
              ],
              gameType: GameType.Ranked,
              gameStatus: GameStatus.Pending,
              gamePlayerLevel: GamePlayerLevel.Master,
              description: "Ranked game",
              images: [
                "https://images.unsplash.com/photo-1459865264687-595d652de67e?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1170&q=80",
                "https://images.unsplash.com/photo-1606925797300-0b35e9d1794e?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1074&q=80",
              ],
              field: {
                id: 2,
                name: "Field 2",
                address: "Address 2",
                latitude: 101,
                longitude: 101,
                createdAt: new Date(),
                updatedAt: new Date(),
                isDeleted: false,
                isActive: true,
              },
              createdAt: new Date(),
              updatedAt: new Date(),
              isDeleted: false,
              isActive: true,
              isPublic: true,
              playerPerTeam: 4,
              price: 200,
              currency: "USD",
              isFree: false,
              isPaid: true,
              startTime: new Date(),
              duration: 120,
            },
            {
              id: 3,
              ownerId: 3,
              players: [mockPlayers[0], mockPlayers[2]],
              gameType: GameType.TeamDraft,
              gameStatus: GameStatus.Completed,
              gamePlayerLevel: GamePlayerLevel.Legend,
              description: "Team draft game",
              images: [
                "https://images.unsplash.com/photo-1589487391730-58f20eb2c308?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1074&q=80",
              ],
              field: {
                id: 3,
                name: "Field 3",
                address: "Address 3",
                latitude: 102,
                longitude: 102,
                createdAt: new Date(),
                updatedAt: new Date(),
                isDeleted: false,
                isActive: true,
              },
              createdAt: new Date(),
              updatedAt: new Date(),
              isDeleted: false,
              isActive: true,
              isPublic: true,
              playerPerTeam: 5,
              price: 300,
              currency: "USD",
              isFree: false,
              isPaid: true,
              startTime: new Date(),
              duration: 150,
            },
            {
              id: 4,
              ownerId: 4,
              players: [
                mockPlayers[0],
                mockPlayers[1],
                mockPlayers[4],
                mockPlayers[3],
              ],
              gameType: GameType.Friendly,
              gameStatus: GameStatus.Active,
              gamePlayerLevel: GamePlayerLevel.Amateur,
              description: "Friendly game 2",
              images: [
                "https://images.unsplash.com/photo-1560272564-c83b66b1ad12?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1287&q=80",
              ],
              field: {
                id: 4,
                name: "Field 4",
                address: "Address 4",
                latitude: 103,
                longitude: 103,
                createdAt: new Date(),
                updatedAt: new Date(),
                isDeleted: false,
                isActive: true,
              },
              createdAt: new Date(),
              updatedAt: new Date(),
              isDeleted: false,
              isActive: true,
              isPublic: true,
              playerPerTeam: 6,
              price: 100,
              currency: "USD",
              isFree: true,
              isPaid: false,
              startTime: new Date(),
              duration: 100,
            },
            {
              id: 5,
              ownerId: 5,
              players: [mockPlayers[1], mockPlayers[2]],
              gameType: GameType.Ranked,
              gameStatus: GameStatus.Pending,
              gamePlayerLevel: GamePlayerLevel.Master,
              description: "Ranked game 2",
              images: [
                "https://images.unsplash.com/photo-1461896836934-ffe607ba8211?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1170&q=80",
              ],
              field: {
                id: 5,
                name: "Field 5",
                address: "Address 5",
                latitude: 104,
                longitude: 104,
                createdAt: new Date(),
                updatedAt: new Date(),
                isDeleted: false,
                isActive: true,
              },
              createdAt: new Date(),
              updatedAt: new Date(),
              isDeleted: false,
              isActive: true,
              isPublic: true,
              playerPerTeam: 8,
              price: 200,
              currency: "USD",
              isFree: false,
              isPaid: true,
              startTime: new Date(),
              duration: 120,
            },
            {
              id: 6,
              ownerId: 6,
              players: [mockPlayers[0], mockPlayers[2]],
              gameType: GameType.TeamDraft,
              gameStatus: GameStatus.Completed,
              gamePlayerLevel: GamePlayerLevel.Legend,
              description: "Team draft game 2",
              images: [
                "https://images.unsplash.com/photo-1600250395178-40fe752e5189?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1170&q=80",
              ],
              field: {
                id: 6,
                name: "Field 6",
                address: "Address 6",
                latitude: 105,
                longitude: 105,
                createdAt: new Date(),
                updatedAt: new Date(),
                isDeleted: false,
                isActive: true,
              },
              createdAt: new Date(),
              updatedAt: new Date(),
              isDeleted: false,
              isActive: true,
              isPublic: true,
              playerPerTeam: 8,
              price: 300,
              currency: "USD",
              isFree: false,
              isPaid: true,
              startTime: new Date(),
              duration: 150,
            },
            {
              id: 7,
              ownerId: 7,
              players: [mockPlayers[0], mockPlayers[1]],
              gameType: GameType.Friendly,
              gameStatus: GameStatus.Active,
              gamePlayerLevel: GamePlayerLevel.Amateur,
              description: "Friendly game 3",
              images: [
                "https://images.unsplash.com/photo-1529900748604-07564a03e7a6?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1170&q=80",
              ],
              field: {
                id: 7,
                name: "Field 7",
                address: "Address 7",
                latitude: 106,
                longitude: 106,
                createdAt: new Date(),
                updatedAt: new Date(),
                isDeleted: false,
                isActive: true,
              },
              createdAt: new Date(),
              updatedAt: new Date(),
              isDeleted: false,
              isActive: true,
              isPublic: true,
              playerPerTeam: 9,
              price: 100,
              currency: "USD",
              isFree: true,
              isPaid: false,
              startTime: new Date(),
              duration: 100,
            },
            {
              id: 8,
              ownerId: 8,
              players: [mockPlayers[1], mockPlayers[2]],
              gameType: GameType.Ranked,
              gameStatus: GameStatus.Pending,
              gamePlayerLevel: GamePlayerLevel.Master,
              description: "Ranked game 3",
              images: [
                "https://images.unsplash.com/photo-1516463439953-eb6a1c2867b4?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1170&q=80",
              ],
              field: {
                id: 8,
                name: "Field 8",
                address: "Address 8",
                latitude: 107,
                longitude: 107,
                createdAt: new Date(),
                updatedAt: new Date(),
                isDeleted: false,
                isActive: true,
              },
              createdAt: new Date(),
              updatedAt: new Date(),
              isDeleted: false,
              isActive: true,
              isPublic: true,
              playerPerTeam: 6,
              price: 200,
              currency: "USD",
              isFree: false,
              isPaid: true,
              startTime: new Date(),
              duration: 120,
            },
            {
              id: 9,
              ownerId: 9,
              players: [mockPlayers[0], mockPlayers[2]],
              gameType: GameType.TeamDraft,
              gameStatus: GameStatus.Completed,
              gamePlayerLevel: GamePlayerLevel.Legend,
              description: "Team draft game 3",
              images: [
                "https://images.unsplash.com/photo-1579952363873-27f3bade9f55?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=435&q=80",
              ],
              field: {
                id: 9,
                name: "Field 9",
                address: "Address 9",
                latitude: 108,
                longitude: 108,
                createdAt: new Date(),
                updatedAt: new Date(),
                isDeleted: false,
                isActive: true,
              },
              createdAt: new Date(),
              updatedAt: new Date(),
              isDeleted: false,
              isActive: true,
              isPublic: true,
              playerPerTeam: 6,
              price: 300,
              currency: "USD",
              isFree: false,
              isPaid: true,
              startTime: new Date(),
              duration: 150,
            },
            {
              id: 10,
              ownerId: 10,
              players: [],
              gameType: GameType.Friendly,
              gameStatus: GameStatus.Active,
              gamePlayerLevel: GamePlayerLevel.Amateur,
              description: "Friendly game 4",
              images: [
                "https://images.unsplash.com/photo-1551958219-acbc608c6377?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1170&q=80",
              ],
              field: {
                id: 10,
                name: "Field 10",
                address: "Address 10",
                latitude: 109,
                longitude: 109,
                createdAt: new Date(),
                updatedAt: new Date(),
                isDeleted: false,
                isActive: true,
              },
              createdAt: new Date(),
              updatedAt: new Date(),
              isDeleted: false,
              isActive: true,
              isPublic: true,
              playerPerTeam: 7,
              price: 100,
              currency: "USD",
              isFree: true,
              isPaid: false,
              startTime: new Date(),
              duration: 100,
            },
            {
              id: 11,
              ownerId: 11,
              players: [],
              gameType: GameType.Ranked,
              gameStatus: GameStatus.Pending,
              gamePlayerLevel: GamePlayerLevel.Master,
              description: "Ranked game 4",
              images: ["https://example.com/image14.jpg"],
              field: {
                id: 11,
                name: "Field 11",
                address: "Address 11",
                latitude: 110,
                longitude: 110,
                createdAt: new Date(),
                updatedAt: new Date(),
                isDeleted: false,
                isActive: true,
              },
              createdAt: new Date(),
              updatedAt: new Date(),
              isDeleted: false,
              isActive: true,
              isPublic: true,
              playerPerTeam: 7,
              price: 200,
              currency: "USD",
              isFree: false,
              isPaid: true,
              startTime: new Date(),
              duration: 120,
            },
            {
              id: 12,
              ownerId: 12,
              players: [],
              gameType: GameType.TeamDraft,
              gameStatus: GameStatus.Completed,
              gamePlayerLevel: GamePlayerLevel.Legend,
              description: "Team draft game 4",
              images: ["https://example.com/image15.jpg"],
              field: {
                id: 12,
                name: "Field 12",
                address: "Address 12",
                latitude: 111,
                longitude: 111,
                createdAt: new Date(),
                updatedAt: new Date(),
                isDeleted: false,
                isActive: true,
              },
              createdAt: new Date(),
              updatedAt: new Date(),
              isDeleted: false,
              isActive: true,
              isPublic: true,
              playerPerTeam: 8,
              price: 300,
              currency: "USD",
              isFree: false,
              isPaid: true,
              startTime: new Date(),
              duration: 150,
            },
            {
              id: 13,
              ownerId: 13,
              players: [],
              gameType: GameType.Friendly,
              gameStatus: GameStatus.Active,
              gamePlayerLevel: GamePlayerLevel.Amateur,
              description: "Friendly game 5",
              images: ["https://example.com/image16.jpg"],
              field: {
                id: 13,
                name: "Field 13",
                address: "Address 13",
                latitude: 112,
                longitude: 112,
                createdAt: new Date(),
                updatedAt: new Date(),
                isDeleted: false,
                isActive: true,
              },
              createdAt: new Date(),
              updatedAt: new Date(),
              isDeleted: false,
              isActive: true,
              isPublic: true,
              playerPerTeam: 5,
              price: 100,
              currency: "USD",
              isFree: true,
              isPaid: false,
              startTime: new Date(),
              duration: 100,
            },
            {
              id: 14,
              ownerId: 14,
              players: [],
              gameType: GameType.Ranked,
              gameStatus: GameStatus.Pending,
              gamePlayerLevel: GamePlayerLevel.Master,
              description: "Ranked game 5",
              images: ["https://example.com/image17.jpg"],
              field: {
                id: 14,
                name: "Field 14",
                address: "Address 14",
                latitude: 113,
                longitude: 113,
                createdAt: new Date(),
                updatedAt: new Date(),
                isDeleted: false,
                isActive: true,
              },
              createdAt: new Date(),
              updatedAt: new Date(),
              isDeleted: false,
              isActive: true,
              isPublic: true,
              playerPerTeam: 5,
              price: 200,
              currency: "USD",
            },
          ] as Game[]);
        }, 2000);
      }).then((games) => games.map((g) => gameListAdapter(g, t))),
    ...options,
  });
}
